### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by boo50** [EraNetwork/Era#3]
I've got an error, while compilating daemon on ubuntu 16.04

 ^
hmq1725/blake.c: At global scope:
hmq1725/blake.c:1119:1: fatal error: opening dependency file obj/hmq1725/blake.d: No such file or directory
 }
 ^
compilation terminated.
makefile.unix:203: recipe for target 'obj/hmq1725/blake.o' failed

**Comment by lhfly5201314** [comment]
Hi,friend!I just met the some issue!And I googled it,then I solved with the below:
1.make a new directory in the eracoin's  src/obj directory,just like this:
    /src/obj/hmq1725
2.After done the above,you will met the next issue,use this link:
[https://github.com/exclusivecoin/Exclusive/issues/1](https://github.com/exclusivecoin/Exclusive/issues/1)

I think the above will be ok.Write here if you have more questions!
Good luck!

**Comment by boo50** [comment]
thanks, solved it with:
mkdir /src/obj/hmq1725
chmod +x src/leveldb/build_detect_platform
cd leveldb && make libleveldb.a libmemenv.a
and finally 
make -f makefile.unix
